services:
  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - ./backend/src:/app   
    develop:
      watch:
        - action: rebuild
          path: backend\requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        - action: restart
          path: /backend/src

