services:
  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - dc_managed_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8080:8000
    volumes:
      - ./backend/src:/app
    depends_on:
      db_service:
        condition: service_healthy

volumes:
  dc_managed_db_data:
